### ISSUE TITLE
Warning: React does not recognize the `marginTop` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `margintop` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### ISSUE THREAD

**Issue by dybbuk555** [dybbuk555/swimming_school_management#47]
I customized a marginTop attribute of one styled component on Material UI and React. But I got this warning.
Warning: React does not recognize the `marginTop` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `margintop` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
I need solutions.

**Comment by dybbuk555** [comment]
I solved.

**Comment by dancerking** [comment]
can you explain more detail again?
