### ISSUE TITLE
hierarchy populate operation on mongoose

### ISSUE THREAD

**Issue by dancerking** [dybbuk555/swimming_school_management#49]
It occurred one issue to execute hierarchy populate operation on mongoose. Please answer with correct examples.

**Comment by dybbuk-dev** [comment]
Well, it is possible to do hierarchy populate operation on mongoose. We can use path item on populate operation.
For example:
.populate{
path: 'lesson'
populate: {
path: 'teacher'
populate: ...
}
}
}

**Comment by dancerking** [comment]
Correct
